import { api } from "@/utils/api";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

const Home: NextPage = () => {
  const [query, setQuery] = useState("");
  const { data, refetch, isFetched } = api.recipes.getRecipes.useQuery(
    { query },
    {
      enabled: false,
    }
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1 className="mt-10 text-center text-2xl font-bold md:mt-0 md:text-5xl">
            Having problem figure out what to eat? No worries. Just search.
          </h1>
        </div>
        <div>
          {isFetched ? (
            <div>
              {data?.results.map((recipe) => (
                <Link key={recipe.id} href={`/recipes/${recipe.id}`}>
                  <div>
                    <h3>{recipe.title}</h3>
                    <Image
                      src={recipe.image}
                      alt={recipe.title}
                      width={250}
                      height={250}
                    />
                  </div>
                </Link>
              ))}
            </div>
          ) : (
            <div>
              <input
                type={`search`}
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder={`Type a recipe...`}
                className={`w-full rounded-md px-3 py-3 font-semibold shadow-sm placeholder:text-gray-600 md:rounded-md md:rounded-r-none md:px-5 md:py-5 md:text-xl`}
              />
              <Link
                href={{
                  pathname: "/recipes",
                  query: { q: query },
                }}
              >
                <button className="rounded-lg bg-orange-500 px-6 py-3">
                  Get recipe
                </button>
              </Link>
            </div>
          )}
        </div>
        <div>
          <h2>Or get random one.</h2>
          <Link href={`/recipes`}>
            <button>Get random</button>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
